-- MySQL Script generated by MySQL Workbench
-- Thu Mar 27 13:43:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema merk2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `merk2` ;

-- -----------------------------------------------------
-- Schema merk2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `merk2` ;
USE `merk2` ;

-- -----------------------------------------------------
-- Table `merk2`.`stand_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`stand_category` ;

CREATE TABLE IF NOT EXISTS `merk2`.`stand_category` (
  `stand_category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stand_category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merk2`.`stand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`stand` ;

CREATE TABLE IF NOT EXISTS `merk2`.`stand` (
  `stand_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `size` ENUM('small', 'medium', 'large') NULL DEFAULT 'small',
  `creation_date` DATE NULL,
  `stand_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`stand_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_stand_stand_category_idx` (`stand_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_stand_stand_category`
    FOREIGN KEY (`stand_category_id`)
    REFERENCES `merk2`.`stand_category` (`stand_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merk2`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`product` ;

CREATE TABLE IF NOT EXISTS `merk2`.`product` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NULL,
  `price` MEDIUMINT UNSIGNED NOT NULL,
  `stock` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `stand_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_stand1_idx` (`stand_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_stand1`
    FOREIGN KEY (`stand_id`)
    REFERENCES `merk2`.`stand` (`stand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merk2`.`seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`seller` ;

CREATE TABLE IF NOT EXISTS `merk2`.`seller` (
  `seller_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `stand_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`seller_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_seller_stand1_idx` (`stand_id` ASC) VISIBLE,
  CONSTRAINT `fk_seller_stand1`
    FOREIGN KEY (`stand_id`)
    REFERENCES `merk2`.`stand` (`stand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merk2`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`client` ;

CREATE TABLE IF NOT EXISTS `merk2`.`client` (
  `client_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merk2`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`sale` ;

CREATE TABLE IF NOT EXISTS `merk2`.`sale` (
  `sale_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `client_id` INT UNSIGNED NOT NULL,
  `seller_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sale_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_sale_seller1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `merk2`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `merk2`.`seller` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merk2`.`sale_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merk2`.`sale_has_product` ;

CREATE TABLE IF NOT EXISTS `merk2`.`sale_has_product` (
  `sale_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` SMALLINT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`sale_id`, `product_id`),
  INDEX `fk_sale_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_sale_has_product_sale1_idx` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_has_product_sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `merk2`.`sale` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `merk2`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
